### ISSUE TITLE
Add function abbreviations support

### ISSUE THREAD

**Issue by aleksandrAndrosov** [interfaced/brightscript-intellij-plugin#13]
As i can see, functions as "?" for "print" are not supported and they make webstorm unable to roll up function code

**Comment by reeFridge** [comment]
@aleksandrAndrosov, can you share some code (or link to the project) which using this print aliases?

**Comment by reeFridge** [comment]
Anyway should be fixed in near release.

**Comment by aleksandrAndrosov** [comment]
![print good](https://user-images.githubusercontent.com/43684584/53718311-7b21ae00-3e63-11e9-844a-575a837f2a42.PNG)
![print no good](https://user-images.githubusercontent.com/43684584/53718313-7b21ae00-3e63-11e9-9046-51b694c9f2eb.PNG)

**Comment by reeFridge** [comment]
@aleksandrAndrosov, can you approve that issue was fixed in latest release?

**Comment by aleksandrAndrosov** [comment]
i've reinstalled plugin. now version is 0.2.0. same problem as shown in screenshots

**Comment by reeFridge** [comment]
![screen shot 2019-03-07 at 10 15 58 pm](https://user-images.githubusercontent.com/12645379/53966866-a4be2c00-4126-11e9-85cd-f79c8dc14e88.png)

Did you restart IDE after reinstalling plugin?

**Comment by aleksandrAndrosov** [comment]
Sorry, i haven't checked different cases
now if you just put "?" something wrong happens. when you put next symbol, everything becomes good

**Comment by aleksandrAndrosov** [comment]
![bug](https://user-images.githubusercontent.com/43684584/54111132-d1569a00-43eb-11e9-8b5f-5dcf434652d6.PNG)

**Comment by aleksandrAndrosov** [comment]
so, probably everything is correct now
