### ISSUE TITLE
Ctrl + '  when few lines of code are selected

### ISSUE THREAD

**Issue by aleksandrAndrosov** [interfaced/brightscript-intellij-plugin#18]
If you want to comment few lines of code, it would be great to have a shortcut like Ctrl+'
and when you are uncommenting them - same same

**Comment by AleksandrSam** [comment]
Before adding this plugin this function works from the box in the WS.
But after adding this plugin this function was broken.
It's issue, not enhancement.
Could you fix it?

**Comment by reeFridge** [comment]
feature added in a643b24bc383e1fb7bf4722846cc10ab5b08be77 and will be included in the next plugin release

(but action would be performed by `Ctrl + /` combination instead of `Ctrl + '`)
