### ISSUE TITLE
Plugin incompatible with new versions of IDE

### ISSUE THREAD

**Issue by optimusdag** [interfaced/brightscript-intellij-plugin#28]
Hi,
The plugin is not compatible with last versions of the IDE.
Plugin Error: Plugin "BrightScript" is incompatible (until build 193.SNAPSHOT < WS-202.6109.29)

**Comment by reeFridge** [comment]
Seems that you are using EAP version of WebStorm.
I have just published new version of plugin for Stable and EAP channels and now it is in pending state, but you can verify that new version fixes your problem by installing plugin from [latest release assets](https://github.com/interfaced/brightscript-intellij-plugin/releases/tag/v0.2.6)

**Comment by optimusdag** [comment]
Thanks!!
